create table if not exists lojas (
  id integer generated by default as identity primary key,
  nome text not null,
  cidade text not null,
  estado text not null
);

create table if not exists setores (
  id integer generated by default as identity primary key,
  nome text not null unique
);

create table if not exists tipos_camera (
  id integer generated by default as identity primary key,
  nome text not null unique
);

create table if not exists dispositivos (
  id integer generated by default as identity primary key,
  nome text not null,
  loja_id integer not null references lojas(id) on delete cascade,
  setor_id integer not null references setores(id),
  tipo_camera_id integer not null references tipos_camera(id),
  ip_camera text null,
  status text not null default 'offline' check (status in ('online', 'offline')),
  temperatura_min numeric null,
  temperatura_max numeric null,
  horario_1 time null,
  horario_2 time null,
  horario_3 time null,
  temperatura_atual numeric null,
  ultima_leitura_at timestamptz null,
  porta_status text null check (porta_status in ('aberta', 'fechada')),
  porta_aberta_em timestamptz null,
  last_seen timestamptz null
);

create index if not exists dispositivos_loja_id_idx on dispositivos(loja_id);
create index if not exists dispositivos_setor_id_idx on dispositivos(setor_id);
create index if not exists dispositivos_tipo_camera_id_idx on dispositivos(tipo_camera_id);
create index if not exists dispositivos_status_idx on dispositivos(status);
create index if not exists dispositivos_last_seen_idx on dispositivos(last_seen);

create table if not exists leituras (
  id integer generated by default as identity primary key,
  dispositivo_id integer not null references dispositivos(id) on delete cascade,
  temperatura numeric not null,
  data_hora timestamptz not null default now(),
  tipo_registro text not null check (tipo_registro in ('automatico', 'tempo_real'))
);

create index if not exists leituras_dispositivo_id_idx on leituras(dispositivo_id);
create index if not exists leituras_data_hora_idx on leituras(data_hora);

create table if not exists eventos (
  id integer generated by default as identity primary key,
  dispositivo_id integer not null references dispositivos(id) on delete cascade,
  tipo_evento text not null check (tipo_evento in ('porta_aberta', 'porta_fechada', 'alarme_disparado', 'temperatura_fora_padrao')),
  data_hora timestamptz not null default now(),
  duracao_segundos integer null check (duracao_segundos is null or duracao_segundos >= 0)
);

create index if not exists eventos_dispositivo_id_idx on eventos(dispositivo_id);
create index if not exists eventos_data_hora_idx on eventos(data_hora);
create index if not exists eventos_tipo_evento_idx on eventos(tipo_evento);

create table if not exists resumo_diario (
  id integer generated by default as identity primary key,
  dispositivo_id integer not null references dispositivos(id) on delete cascade,
  data date not null,
  total_aberturas integer not null default 0,
  tempo_total_aberto integer not null default 0,
  total_alarmes integer not null default 0,
  unique (dispositivo_id, data)
);

create index if not exists resumo_diario_data_idx on resumo_diario(data);

create table if not exists users (
  id integer generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

